<!DOCTYPE html> 
<html> 
	<head> 
	<title>Lolla Picks - An unofficial app of Lollapalooza</title> 
	<meta name="viewport" content="width=device-width; initial-scale=1.0; minimum-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
        <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
	<link rel="icon" type="image/ico" href="favicon.ico"/>
</head> 
<body> 

<div data-role="page">
	<div data-role="header">
	    <h1>Artists</h1>
	    <a data-rel="back" href="index.php" data-icon="arrow-l" data-direction="reverse">Back</a>
	    <a data-transition="reverse slide" href="index.php" data-icon="home" data-iconpos="notext" >Home</a>
	</div><!-- /header -->
	<div data-role="content">
            <div data-role='collapsible-set'>
            {% for item in artist_array %}
                {{ item }}
            {% endfor %}
            </div>
	    
	</div><!-- /content -->
</div><!-- /page -->
    
</body>
</html>