<!DOCTYPE html> 
<html> 
	<head> 
	<title>Lolla Picks - An unofficial app of Lollapalooza</title> 
	<meta name="viewport" content="width=device-width; initial-scale=1.0; minimum-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
        <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
	<link rel="icon" type="image/ico" href="favicon.ico"/>
</head> 
<body> 
{% include 'analytics.inc' %}
<div data-role="page">
	<div data-role="header">
	    <h1>Search results for: {{ title }} by {{ artist }}</h1>
	    <a data-rel="back" href="artist.php?id={{ id }}" data-icon="arrow-l" data-direction="reverse">Back</a>
	    <a data-transition="reverse slide" href="index.php" data-icon="home" data-iconpos="notext" >Home</a>
	</div><!-- /header -->
	<div data-role="content">
            <div data-role='controlgroup'>
            {% for song in songs %}
                <a class="song" href="" data-role="button" data-icon="plus" data-iconpos="right" data-artist="{{ artist }}" data-id="{{ id }}" data-title="{{ song }}">{{ song }}</a>
            {% endfor %}
            </div>
	    <script>
                $('.song').unbind('click');
                $('.song').click(function(){
                    $.mobile.showPageLoadingMsg();
                    var title = $(this).data('title');
                    var id = $(this).data('id');
                    var artist = $(this).data('artist');
                    var url = 'request.php?title='+escape(title)+'&id='+escape(id)+'&artist='+escape(artist);
                    var request = new XMLHttpRequest();
                    request.open("GET",url,false);
                    request.send();
                    var response = request.responseText;
                    $.mobile.hidePageLoadingMsg();
                    if(response != 0) alert('Sorry, song could not be found.');
                    else alert('Song requested.');
                    location.replace("artist.php?id="+id);
                });
            </script>
            <a href="http://the.echonest.com/"><img src="http://the.echonest.com/media/images/logos/EN_P_on_White_Horizontal.gif"/></a>
	</div><!-- /content -->
</div><!-- /page -->
    
</body>
</html>